import Vue from 'vue';
import {
    Search,
    Swipe,
    SwipeItem,
    Grid,
    GridItem,
    Icon,
    Tag,
    List,
    CellGroup,
    DropdownMenu,
    DropdownItem,
    Empty,
    Toast,
    Tabbar,
    TabbarItem,
    Col,
    Row,
    Field,
    Form,
    Button,
    Cell,
    Popup,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Sku,
    Checkbox,
    CheckboxGroup,
    Card,
    SubmitBar,
    Stepper,
    SwipeCell,
    Tab,
    Tabs,
    Pagination,
    Sidebar,
    SidebarItem
} from 'vant';


Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Pagination);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(SwipeCell);
Vue.use(Stepper);
Vue.use(SubmitBar);
Vue.use(Card);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Sku);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Popup);
Vue.use(Cell);
Vue.use(Button);
Vue.use(Form);
Vue.use(Field);
Vue.use(Col);
Vue.use(Row);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Toast);
Vue.use(Empty);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(CellGroup);
Vue.use(List);
Vue.use(Tag);
Vue.use(Icon);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Search);